create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password text not null,
  role text default 'admin',
  specialty text default 'إدارة',
  created_at timestamptz default now()
);

create table if not exists patients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  age text,
  gender text,
  address text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists visits (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id) on delete cascade,
  bp text,
  pulse text,
  temp text,
  o2 text,
  bg text,
  complaint text,
  diagnosis text,
  procedure text,
  treatment text,
  provider text,
  specialty text,
  created_at timestamptz default now()
);

create table if not exists prescriptions (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id) on delete cascade,
  medicines jsonb default '[]',
  notes text,
  provider text,
  specialty text,
  created_at timestamptz default now()
);

insert into users (name,email,password,role,specialty)
values ('Admin','admin@clinic.local','Admin12345','admin','إدارة')
on conflict (email) do nothing;
